// <auto-generated />
using System;
using BankReconciliation.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankReconciliation.DAL.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260907125002_AddReconciliationResult")]
    partial class AddReconciliationResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankReconciliation.Domain.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsReconciled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MatchedLedgerTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReconciliationResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReconciliationResultId");

                    b.ToTable("BankTransactions");
                });

            modelBuilder.Entity("BankReconciliation.Domain.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsReconciled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MatchedBankTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReconciliationResultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReconciliationResultId");

                    b.ToTable("LedgerTransactions");
                });

            modelBuilder.Entity("BankReconciliation.Domain.ReconciliationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalBankBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalLedgerBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ReconciliationResults");
                });

            modelBuilder.Entity("BankReconciliation.Domain.BankTransaction", b =>
                {
                    b.HasOne("BankReconciliation.Domain.ReconciliationResult", null)
                        .WithMany("BankTransactions")
                        .HasForeignKey("ReconciliationResultId");
                });

            modelBuilder.Entity("BankReconciliation.Domain.LedgerTransaction", b =>
                {
                    b.HasOne("BankReconciliation.Domain.ReconciliationResult", null)
                        .WithMany("LedgerTransactions")
                        .HasForeignKey("ReconciliationResultId");
                });

            modelBuilder.Entity("BankReconciliation.Domain.ReconciliationResult", b =>
                {
                    b.Navigation("BankTransactions");

                    b.Navigation("LedgerTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
